# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [fso13]
yandex: # Replace with up to 4 custom sponsorship URLs e.g., ['https://fso13.github.io/dnd5-android/']
