sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

before_install:
  - chmod +x gradlew

script:
  - "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"

after_success:
  - sh set_tags.sh

notifications:
  email: true

deploy:
  provider: releases
  api_key:
    secure: wy43X9WESaODgKXr/ccu8OneJQzqrzy84XZcZ1KA74HN2oZzm+NAZbm1FcrzUBbyvtDWMtV8TDArsYSs4SpMMpeSdJbTkK/IMhhFZxvyQ4XBM6YEdkCKnIuLFuFTgIicHlvtbujClOLX0n+dyAKhFyXBH2N53QurmeqlLaYcMXJCdhtnNw7H+8jB/BOvhlR1j5OpG4gQQjio+1YTNGvKu6b0l8yYcLR3i0+YLVhIozwbet12GXrY/nvJAd5fwKe5hqHpGqMIVEqtSBIA+nfijPOYclHal7D3BfRP77jO/dklkAOygLxEzZQiVkfTIWREBbOsllj5bivCbZUmKhQc1lo/Wp+XPC+AO8mnBVOfYHW9l62e+pVieGDdbAdKw7vPIXBHmw2QTSbboRnQMHqU+tNXb2BmZkJGtZaHDwoPZ6xjsbxctSCpm8mn+VV1uOSBp7mHx4iXXqW+Q5YiQ2d5I3fdiAko54g4hT40KIYfSpE4022kzF42BU3apzCnpRhQnAvJid3KEdUAXANXkSxo00WC0lEx2LzxDKzNrheEmPb/uXAQa3OwpKgMP/yI1mrZ0IvAAc9q6NNxHJPeKil6yVQRLexGs3QqjAEwbN4pw1mq1V4zzoBi3Vxb9czKl6iAmVYvF1OY+ZqBHJTBdCHiTiOEbDZVG5yr7j+8VGL/lJw=
  file:  app/build/outputs/apk/release/app*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: fso13/dnd5-android


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"