language: minimal
os: linux
dist: xenial
group: stable
sudo: required
git:
  depth: false
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    # For updates check developer.android.com/studio#downloads (current 26.1.1)
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache/

stages:
  - name: Build and deploy release on tags
    if: tag IS present
notifications:
  slack:
    #    if: tag IS present
    rooms:
      - secure: G3o0JzskRQhXQAviU+q2IadlUOD03xW0b6CsMr8Nq/iASIPGOTD0sNeZ9UN+bMYGd/a/sD3s0jcbDRww0iFZx4LxfS7QAZdVrbsqpv6O1NhEEwT53Dg5MZLXZbi0INOvdIvlICol3p6/74ao18+XgIQKbq4jtN+YTTTCo+9D4BAdWXZ+YUKyjb0WluepXIQgzQ7awCAWoOmHJz8POO9I87dWDCcs2P7VmSAAq185qKMk7FQnTnwW0+KUM7V2HIceBGje9O0mtnjMUr86TLiEfAieK8SPJe7/FPtxT9UT8+hb4DNi/jl27KFVfTGcZoN5tQDeK0qE59pgYzont85tpYFI1yk9Jf5VyvcSllQlGY4Yg8D1yyQeIBAVVAjqvox6eiJ3t2qDueXosCidx0lesTgMP0tP50KCzfyjKtFqCC1SJdoTnriSHopqQmHiJFbbQILklpx7AgBALCKbIqMXBKKSjYa5N0hs4ZgH0QS2ROEJ0UNo6ddjtUcLxFJB6j5kMTsZINCJvufEDpqH3EDumvl5Mz0aUB2LN4Ie2VRFeFloKnDxv6Zawkc/rKr8Ra9YMGMmHciK1pvmnW3htValpdIe61OMtyENAAhseuyN4iOvmHpXqhcNCYC9Uz0R2LEFEgpiiPlFlOSSLITYxy2cHuFa+M6jagolY2fy0gzoBbs=
    on_success: always
    on_failure: always
    template:
      - "Repo %{repository_slug} %{result} build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch %{branch}."
      - "Execution time: %{duration}"
      - "Message: %{message}"
android_phases:
  - phase: &before_install
      # check if OpenJDK8 is installed and install if missing
      - if ! dpkg -s openjdk-8-jdk >/dev/null 2>&1; then sudo apt-get update; sudo apt-get install openjdk-8-jdk; fi
      - java -version
      # print available java versions with their path (must contain java-8-openjdk-amd64)
      - sudo update-alternatives --config java
      # set JAVA_HOME path
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      # download und unzip Android SDK Tools
      - wget -q https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
      - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
      # set SDK Tools path variable and ANDROID_HOME
      - export PATH=$PATH:$HOME/sdk/tools/bin
      - export ANDROID_HOME=$HOME/sdk
      # create empty cfg file to prevent sdkmanager warning message
      - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
  - phase: &install
      # latest SDK Platform-Tools
      - yes | sdkmanager "platform-tools" >/dev/null
      # defined SDK Platform
      - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL" >/dev/null
      # defined SDK Build-Tools
      - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
      # list installed and available packages
      - sdkmanager --list
  - phase: &before_script
      # set executable flag for gradle wrapper
      - chmod +x gradlew
      # create dir for gradle settings
      - mkdir -p $HOME/.gradle
      # disable gradle daemon for current user
      - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
      # set gradle log format to plain
      - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties
      # enable gradle build cache
      - echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
      # log all gradle warnings
      - echo "org.gradle.warning.mode=all" >> $HOME/.gradle/gradle.properties
  - phase: &before_cache
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
      - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
      - rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
      - rm -f  $HOME/.gradle/caches/*/executionHistory/executionHistory.lock
      - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
      - rm -f  $HOME/.gradle/caches/journal-1/journal-1.lock
      - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
      - rm -f  $HOME/.gradle/caches/user-id.txt.lock
      # only cache last gradle version used by the wrapper
      # list content in wrapper/dist sorted by modification time and remove entries starting by the second entry
      - ls -d $HOME/.gradle/wrapper/dists/* -1t | tail -n +2 | xargs rm -rf
  - phase: &deploy
      provider: releases
      edge: true
      api_key: $github_token
      file_glob: true
      file:
        - $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/*.apk
        - $TRAVIS_BUILD_DIR/app/build/outputs/mapping/release/mapping.txt
      skip_cleanup: true
      draft: false
      on:
        repo: fso13/dnd5-android
        tags: true
      name: $TRAVIS_TAG
      tag_name: $TRAVIS_TAG
      body: "Generated release from Travis CI for build $TRAVIS_BUILD_NUMBER"

jobs:
  include:
    - stage: Build debug
      before_install: *before_install
      install: *install
      before_script: *before_script
      script: "./gradlew assembleDebug --scan"
      before_cache: *before_cache
    - stage: Build and deploy release on tags
      before_install: *before_install
      install: *install
      before_script: *before_script
      script: "./gradlew assembleRelease --scan"
      before_cache: *before_cache
      deploy: *deploy