name: Android CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  my-build:
    name: Build Debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
          uses: xdtianyu/actions-android-ci@v1.0.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleDebug